<<<<<<< HEAD
=======
# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android


>>>>>>> parent of d78fc60... Revert "Merge branch 'develop' of https://github.com/tstevanovic/covid-safe-paths into develop"
trigger:
- master

pool:
<<<<<<< HEAD
  vmImage: 'ubuntu-latest'
=======
  vmImage: 'macos-latest'
>>>>>>> parent of d78fc60... Revert "Merge branch 'develop' of https://github.com/tstevanovic/covid-safe-paths into develop"

name: $(date:yyyy).$(Month)$(rev:.r)

steps:
<<<<<<< HEAD

- script: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

- script: yarn install

=======
- script: yarn install
>>>>>>> parent of d78fc60... Revert "Merge branch 'develop' of https://github.com/tstevanovic/covid-safe-paths into develop"
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'android/gradlew'
    workingDirectory: 'android/'
    options: '-PversionName=$(Build.BuildNumber) -PversionCode=$(Build.BuildId)'
    tasks: 'assembleRelease'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    gradleOptions: '-Xmx3072m'

- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'my-upload-key.keystore'
    apksignerKeystorePassword: '$(KeyStorePassword)'
    apksignerKeystoreAlias: '$(KeyAlias)'
    apksignerKeyPassword: '$(KeyPassword)'
    zipalign: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'android/app/build/outputs/apk/release'
    ArtifactName: 'drop'
<<<<<<< HEAD
    publishLocation: 'Container'

# Distribute the app
- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'EYAppCenter'
    appSlug: 'EYChile/SafePaths'
    appFile: 'android/app/build/outputs/apk/release/*.apk'
    symbolsOption: 'Android'
    releaseNotesOption: 'input'
    releaseNotesInput: 'DevTest'
    isMandatory: true
    destinationType: 'groups'
=======
    publishLocation: 'Container'
>>>>>>> parent of d78fc60... Revert "Merge branch 'develop' of https://github.com/tstevanovic/covid-safe-paths into develop"
